### ISSUE TITLE
[frontend][issues] Small Issues to Fix

### ISSUE THREAD

**Issue by anonymous-sidhax** [Collaborative-Open-Source-Projects/zenith-ide#20]
- Run Button and Download Button Colors (Can we keep something different - purple color is looking odd for dark theme)
- Run Button and Download Button Indentation fix
- Can we update the language selector color / bg for dark and light theme (currently it is the same for both).

![image](https://github.com/user-attachments/assets/f93d830c-1a68-400a-b934-42409ba94428)

**Comment by shawaiz-khan** [comment]
I will do it as soon as I get free
